twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%\public\img\header': images
    # Paramétrage du thème bootstrap    
    form_themes: ['bootstrap_4_layout.html.twig']
